export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CHECK_LOGIN_STATUS = "CHECK_LOGIN_STATUS";
export const SHOW_SIGNIN = "SHOW_SIGNIN";
export const HIDE_SIGNIN = "HIDE_SIGNIN";

export const PROFILE_INIT = "PROFILE_INIT";
export const PROFILE_INIT_START = "PROFILE_INIT_START";
export const PROFILE_INIT_SUCCESS = "PROFILE_INIT_SUCCESS";
export const PROFILE_INIT_FAIL = "PROFILE_INIT_FAIL";
export const UNFOLLOW_INIT = "UNFOLLOW_INIT";
export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_FAIL = "UNFOLLOW_FAIL";
export const FOLLOW_INIT = "FOLLOW_INIT";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAIL = "FOLLOW_FAIL";

export const PLAYER_INIT_START = "PLAYER_INIT_START";
export const PLAYER_INIT_SUCCESS = "PLAYER_INIT_SUCCESS";
export const PLAYER_INIT_FAIL = "PLAYER_INIT_FAIL";

export const GAME_INIT_START = "GAME_INIT_START";
export const GAME_INIT_SUCCESS = "GAME_INIT_SUCCESS";
export const GAME_INIT_FAIL = "GAME_INIT_FAIL";
