export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CHECK_LOGIN_STATUS = "CHECK_LOGIN_STATUS";

export const PROFILE_INIT = "PROFILE_INIT";
export const PROFILE_INIT_START = "PROFILE_INIT_START";
export const PROFILE_INIT_SUCCESS = "PROFILE_INIT_SUCCESS";
export const PROFILE_INIT_FAIL = "PROFILE_INIT_FAIL";

export const PLAYER_INIT_START = "PROFILE_INIT_START";
export const PLAYER_INIT_SUCCESS = "PROFILE_INIT_SUCCESS";
export const PLAYER_INIT_FAIL = "PROFILE_INIT_FAIL";
